joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: cadera
  pid: {p: 4000, i: 680, d: 720}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: hombro
  pid: {p: 4000, i: 820, d: 800}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: codo
  pid: {p: 1500, i: 500, d: 100}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: mano
  pid: {p: 1500, i: 500, d: 100}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper
#  joint: gripper2
  pid: {p: 4000, i: 60, d: 20}
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper2
  pid: {p: 4000, i: 60, d: 20}
